(()=>{
  const config=window.TRUEANALYZER_CONFIG||{};
  const ready=Boolean(config.apiBaseUrl&&config.auth0Domain&&config.auth0ClientId&&window.createAuth0Client);
  if(!ready)return;
  const state={client:null,token:null,organizationId:localStorage.getItem("trueanalyzer.organizationId")||"",datasetId:""};
  const api=async(path,options={})=>{const headers={...(options.headers||{}),authorization:`Bearer ${state.token}`,"content-type":"application/json"};if(state.organizationId)headers["x-organization-id"]=state.organizationId;const response=await fetch(`${config.apiBaseUrl.replace(/\/$/,"")}${path}`,{...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"The request could not be completed.");return body};
  const setSessionLabel=async()=>{const slot=document.querySelector(".header-actions");if(!slot)return;let button=document.querySelector("#remoteSignIn");if(!button){button=document.createElement("button");button.id="remoteSignIn";button.className="team-button";slot.prepend(button)}const user=await state.client.getUser();button.textContent=user?`Signed in: ${user.name||user.email||"User"}`:"Sign in";button.onclick=()=>state.client.loginWithRedirect({authorizationParams:{audience:config.auth0Audience,redirect_uri:location.origin}})};
  const ensureWorkspace=async()=>{if(state.organizationId)return;const workspace=await api("/api/onboarding",{method:"POST",body:JSON.stringify({})});state.organizationId=workspace.organization.id;localStorage.setItem("trueanalyzer.organizationId",state.organizationId)};
  const parseFile=async file=>{const text=await file.text();if(file.name.toLowerCase().endsWith(".json")){const parsed=JSON.parse(text);if(!Array.isArray(parsed))throw new Error("JSON data must be a list of rows.");return parsed}const lines=text.trim().split(/\r?\n/);const headers=lines[0].split(",").map(value=>value.trim().replace(/^"|"$/g,""));return lines.slice(1).filter(Boolean).map(line=>{const values=line.match(/(?:[^,"]+|"[^"]*")+/g)||[];return Object.fromEntries(headers.map((header,index)=>[header,(values[index]||"").trim().replace(/^"|"$/g,"")]))})};
  const showResult=result=>{const output=result.result||result;const title=document.querySelector(".insight-card h2"),copy=document.querySelector(".insight-copy");if(output.forecast){title.textContent=`Forecast total: ${money(output.totalForecast)}`;copy.textContent=`${output.method}. Validation: ${output.validation?.mapePercent}% MAPE across ${output.validation?.holdoutPeriods} held-out periods. ${output.limitation}`}else if(output.comparison){title.textContent=`Result: ${money(output.value)}`;copy.textContent=`Baseline: ${money(output.comparison.baseline)}. Difference: ${money(output.comparison.difference)} (${output.comparison.percentChange?.toFixed(1)??"n/a"}%).`}else if(Array.isArray(output.values)){title.textContent=`Analysis found ${output.values.length} result(s).`;copy.textContent=`${output.method}. Review the chart and source data before acting.`}else{title.textContent=`Result: ${money(output.value||0)}`;copy.textContent=`${output.method}. ${output.recordsUsed||0} records were used.`}window.updateAssurance?.({method:output.method||"Governed API analysis",note:`Dataset version ${result.datasetVersion||"current"}; ${output.evidence?.recordsMatched||output.recordsUsed||0} records used.`,confidence:"Calculated by the deployed API and recorded in its audit trail."});toast("Live API analysis complete.")};
  const runQuestion=async question=>{if(!state.datasetId)throw new Error("Upload a dataset after signing in before running an API analysis.");const plan=await api("/api/analyses/plan",{method:"POST",body:JSON.stringify({datasetId:state.datasetId,question})});const result=await api("/api/analyses",{method:"POST",body:JSON.stringify({datasetId:state.datasetId,question,plan})});showResult(result);addHistory(question)};
  const connectUi=()=>{const fileInput=document.querySelector("#fileInput");fileInput.onchange=async event=>{const selected=event.target.files[0];if(!selected)return;try{const parsed=await parseFile(selected);if(!parsed.length)throw new Error("The file has no data rows.");rows=parsed;file=selected.name;stats();table();document.querySelector("#previewTitle").textContent=file;document.querySelector("#uploadModal").classList.add("hidden");document.querySelector("#datasets").classList.remove("hidden");state.datasetId=(await api("/api/datasets",{method:"POST",body:JSON.stringify({name:file,rows:parsed,classification:"internal"})})).id;toast("Dataset uploaded to the live workspace.")}catch(error){toast(error instanceof Error?error.message:"We could not upload that file.")}};const fallback=window.enterpriseAnalyze;window.enterpriseAnalyze=question=>runQuestion(question).catch(error=>{toast(error instanceof Error?error.message:"Live analysis failed.");fallback(question)});document.querySelector("#sendQuery").onclick=()=>window.enterpriseAnalyze(document.querySelector("#queryInput").value);document.querySelector("#queryInput").addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter"){event.preventDefault();event.stopImmediatePropagation();window.enterpriseAnalyze(event.target.value)}},true)};
  (async()=>{state.client=await createAuth0Client({domain:config.auth0Domain,clientId:config.auth0ClientId,authorizationParams:{redirect_uri:location.origin,audience:config.auth0Audience}});window.datalystAuth={login:()=>state.client.loginWithRedirect({authorizationParams:{audience:config.auth0Audience,redirect_uri:location.origin}}),signup:()=>state.client.loginWithRedirect({authorizationParams:{audience:config.auth0Audience,redirect_uri:location.origin,screen_hint:"signup"}})};if(location.search.includes("code=")&&location.search.includes("state=")){await state.client.handleRedirectCallback();history.replaceState({},document.title,location.pathname)}if(await state.client.isAuthenticated()){state.token=await state.client.getTokenSilently();await ensureWorkspace()}await setSessionLabel();connectUi()})().catch(error=>console.warn("Remote demo setup failed",error));
})();
