let wizardStep=1, objective='Understand performance';
const wm=document.querySelector('#wizardModal'), steps=[...document.querySelectorAll('.wizard-step')], navSteps=[...document.querySelectorAll('.wizard-sidebar li')];
function showWizardStep(n){wizardStep=n;steps.forEach(s=>s.classList.toggle('hidden',Number(s.dataset.step)!==n));navSteps.forEach((s,i)=>s.classList.toggle('current',i===n-1));document.querySelector('#wizardProgress').textContent=`${n} of 4`;document.querySelector('#wizardBack').disabled=n===1;document.querySelector('#wizardNext').textContent=n===4?'Run analysis ✦':'Continue →';if(n===4){document.querySelector('#reviewData').textContent=file;document.querySelector('#reviewObjective').textContent=objective;document.querySelector('#reviewQuestion').textContent=document.querySelector('#wizardQuestion').value||'Performance analysis across the current dataset'}}
document.querySelector('#openWizard').onclick=()=>{document.querySelector('#wizardFile').textContent=file;document.querySelector('#wizardFileDetails').textContent=`${rows.length.toLocaleString()} rows · ${rows[0]?Object.keys(rows[0]).length:0} fields · Internal`;showWizardStep(1);wm.classList.remove('hidden')};
document.querySelector('#closeWizard').onclick=()=>wm.classList.add('hidden');
document.querySelector('#wizardBack').onclick=()=>showWizardStep(Math.max(1,wizardStep-1));
document.querySelector('#wizardNext').onclick=()=>{if(wizardStep<4)showWizardStep(wizardStep+1);else{const q=document.querySelector('#wizardQuestion').value||`${objective} for the current data`;wm.classList.add('hidden');enterpriseAnalyze(q);document.querySelector('#insights').scrollIntoView({behavior:'smooth',block:'start'});toast('Enterprise analysis created and logged to the audit trail.')}};
document.querySelectorAll('.objective').forEach(button=>button.onclick=()=>{document.querySelectorAll('.objective').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');objective=button.dataset.objective});
document.querySelector('#wizardAddSource').onclick=()=>{wm.classList.add('hidden');document.querySelector('#uploadModal').classList.remove('hidden')};
