"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api-client";

type Metric = { id: string; name: string; expression: { operation: "sum" | "average"; field: string }; status: string };
export function MetricGovernance({ columns }: { columns: string[] }) {
  const [metrics, setMetrics] = useState<Metric[]>([]), [name, setName] = useState(""), [field, setField] = useState(""), [operation, setOperation] = useState<"sum" | "average">("sum"), [message, setMessage] = useState("");
  const load = () => api<Metric[]>("/api/metrics").then(setMetrics).catch(() => setMessage("Metric definitions are unavailable right now."));
  useEffect(() => { load(); }, []);
  const create = async () => { if (!name.trim() || !field) return; try { await api("/api/metrics", { method: "POST", body: JSON.stringify({ name, expression: { operation, field } }) }); setName(""); setMessage("Metric saved as a draft for approval."); load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Metric could not be saved."); } };
  return <details className="rounded-xl border border-border bg-surface p-4"><summary className="cursor-pointer font-semibold">Metric governance</summary><p className="mt-2 text-sm text-text-secondary">Create shared definitions so the team calculates important measures the same way.</p><div className="mt-3 flex flex-wrap gap-2"><input value={name} onChange={event => setName(event.target.value)} placeholder="Metric name, e.g. Total Sales" className="rounded border border-border bg-background p-2 text-sm text-white"/><select value={operation} onChange={event => setOperation(event.target.value as "sum" | "average")} className="rounded border border-border bg-background p-2 text-sm text-white"><option value="sum">Sum</option><option value="average">Average</option></select><select value={field} onChange={event => setField(event.target.value)} className="rounded border border-border bg-background p-2 text-sm text-white"><option value="">Choose a field</option>{columns.map(column => <option key={column}>{column}</option>)}</select><button onClick={create} className="rounded bg-primary px-3 py-2 text-sm font-semibold">Save draft</button></div>{message ? <p className="mt-2 text-sm text-text-secondary">{message}</p> : null}{metrics.length ? <ul className="mt-3 space-y-1 text-sm text-text-secondary">{metrics.map(metric => <li key={metric.id}><b className="text-white">{metric.name}</b> = {metric.expression.operation}({metric.expression.field}) · {metric.status}</li>)}</ul> : <p className="mt-3 text-sm text-text-muted">No approved metrics yet.</p>}</details>;
}
