type Row = Record<string, unknown>;
const number = (value: unknown) => { const parsed = Number(String(value ?? "").trim().replace(/^\((.*)\)$/, "-$1").replace(/[$,%\s,]/g, "")); return Number.isFinite(parsed) ? parsed : null; };
const find = (columns: string[], expression: RegExp) => columns.find(column => expression.test(column));
const format = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value);
function grouped(rows: Row[], field: string, dimension: string) { const values = new Map<string, { total: number; count: number }>(); rows.forEach(row => { const value = number(row[field]); if (value === null) return; const key = String(row[dimension] ?? "Unknown"); const current = values.get(key) || { total: 0, count: 0 }; current.total += value; current.count++; values.set(key, current); }); return [...values].map(([label, value]) => ({ label, ...value })).sort((a, b) => b.total - a.total); }

export function buildBriefing(rows: Row[], columns: string[]) {
  const metric = find(columns, /total.?price|revenue|sales|amount|value/i) || columns.find(column => rows.some(row => number(row[column]) !== null));
  if (!metric) return { briefing: "## Executive briefing\n\nNo reliable numeric measure was detected. Add a sales, revenue, cost, quantity, or other numeric field before requesting business recommendations." };
  const values = rows.map(row => number(row[metric])).filter((value): value is number => value !== null);
  const total = values.reduce((sum, value) => sum + value, 0), average = total / Math.max(values.length, 1);
  const region = find(columns, /region|country|market|territory|area/i), product = find(columns, /product|category|item|sku/i), returned = find(columns, /returned|return.?flag/i), discount = find(columns, /discount/i);
  const sections = ["## Executive briefing", `**Headline:** ${format(total)} in ${metric} across ${values.length.toLocaleString()} valid records; average value is ${format(average)} per record.`];
  const working: string[] = [], risks: string[] = [], recommendations: string[] = [];
  if (region) { const ranking = grouped(rows, metric, region); if (ranking.length) { const leader = ranking[0], weak = ranking.at(-1)!; working.push(`**${leader.label}** is the largest ${region} at ${format(leader.total)} (${((leader.total / total) * 100).toFixed(1)}% of total).`); risks.push(`**${weak.label}** is the smallest ${region} at ${format(weak.total)}; compare its mix, availability, pricing, and service experience with ${leader.label}.`); recommendations.push(`Create a recovery plan for ${weak.label} and replicate the strongest practices from ${leader.label}, with weekly tracking of ${metric} and order value.`); } }
  if (product) { const ranking = grouped(rows, metric, product); if (ranking.length) { const leader = ranking[0]; working.push(`**${leader.label}** is the leading ${product} by ${metric} at ${format(leader.total)}.`); recommendations.push(`Protect availability and commercial support for ${leader.label}, then test which parts of its offer can be applied to lower-performing ${product} lines.`); } }
  if (returned) { const flags = rows.map(row => number(row[returned])).filter((value): value is number => value !== null); if (flags.length) { const rate = flags.filter(value => value > 0).length / flags.length; risks.push(`The recorded return rate is **${(rate * 100).toFixed(1)}%**. Validate return reasons and the refund value before treating gross sales as net performance.`); recommendations.push(`Prioritize a return-reduction review for the highest-value products and regions; measure return rate, refund value, and root cause together.`); } }
  if (discount) { const discounted = rows.map(row => number(row[discount])).filter((value): value is number => value !== null); if (discounted.length) { const avgDiscount = discounted.reduce((sum, value) => sum + value, 0) / discounted.length; risks.push(`Average recorded discount is **${(avgDiscount <= 1 ? avgDiscount * 100 : avgDiscount).toFixed(1)}%**. The dataset alone does not prove that deeper discounting creates profitable growth.`); recommendations.push("Run controlled promotion tests by product and region, judging success on net revenue, order value, and returns—not order volume alone."); } }
  sections.push("\n### What is working", ...(working.length ? working.map(item => `- ${item}`) : ["- The data has a usable numeric measure for performance tracking."]));
  sections.push("\n### Risks to investigate", ...(risks.length ? risks.map(item => `- ${item}`) : ["- Add customer, cost, and outcome fields to identify the most important risks."]));
  sections.push("\n### Prioritized recommendations", ...recommendations.slice(0, 4).map((item, index) => `${index + 1}. ${item}`));
  sections.push("\n*Decision note: this briefing is based on recorded values in the uploaded dataset. Add cost, margin, and refund amounts to evaluate profitability rather than sales alone.*");
  return { briefing: sections.join("\n") };
}
